dist: xenial
language: python
python:
- '3.6'
- '3.7'
- '3.8'
install:
- pip install --upgrade -e .[test]
script:
- pytest --cov=./
deploy:
  provider: pypi
  user: jcklie
  skip_existing: true
  password:
    secure: X3CAzSzt2nSmt4Q24MWlMFigyb0DAfkhGYxa2YaZQH3uTgMg7L/6QswTyevutHhEfhN/sgRvU7tsGvamRX6QA4r39wfFS1ovknQsANHIGb+tul4dSNfvs4UGlUkGma6D1MnT4kR28Ek69obBCzMbwGu0JVOhH+/GxHTEaufynfp7ELDZeNFgD7uS9eiuA05Q4FGdRhbBUZBVYJcW8g7KZlPzHfDNW2MMpynCUpBnD/rDl6kFnq8SfQN/FMlB16N2yjFkm4T6v2+naDf8L28wm10BZY/b1EbO3ShqLaYMGQSWJajHZFofZejOed5aQJPHKLeqJZl8b8ewzyWld27AeI/6te4PygZwgJipdbcWTd8b19zcY/a/nxTN+ap56On1f7tak9kXrlkwIu5a3fRQRKSmnibhc6hCUElwjaiMDP8XCR4kcMZ2ahebsIKifxAdziWreOmRoqNzKr3nXcE3JfW+pW9i9EqstI43tf2eB1s/PfxGUj15zZkNCxJv82Et+al48j+tCvmnYjfNtq9FrnE74K1yqQULkTjAYTHYgIYoe9EN5wBPmQwfMDO9eHMjVxDltgqcba6orP8Pm6Cw/VBQg27b/eauZ3CBo9lhgpNPbvkl6zlXa2zg6Zeq1OpNPoMKNTLUBumyY6vwF96SDTawILHRSqz8K312mk2Iugs=
  on:
    tags: true
after_success:
- codecov
